@startuml

Bruger"1" --* "1..*" Universitet
Bruger <|-- Studerende
Bruger <|-- Lærer
Bruger <|-- SkemaSekretær
Studerende"1" --o "1" Studieretning
Studieretning"1" --* "4..*" Semester
Semester"1" --* "2..4" Kurser
Lærer"1" --o "1..*" Kurser
Kurser"1" --o "1..*" Skema
SkemaSekretær"1" --o "1..*" Skema
Lærer"1" --o "1" Skema
Skema"1" --* "1..*" Forelæsning
Forelæsning"1" --o "1" Lokaler


abstract class Bruger{
    Navn: str
    Telefonnummer: varchar
    Adresse: str
    E-mail: invarchar255
    CPR-nummer: varchar
    }
class Studerende{
    Student ID: int
    Studieretning: Studieretning
    Hold: str
    --
    SeSkema():
    }
class SkemaSekretær{
    Medarbejder ID: int
    Fakultet: str
    --
    RedigereSkema():
    BesvareAnmodning():
    SeSkema():
    }
class Universitet{
    Universitets ID: int
    Fakultet: str
    }
class Lærer{
    Medarbejder ID: int
    Kursusliste: list
    --
    ForeslåSkemaændring():
    SeSkema():
    }
class Lokaler{
    Lokation ID: int
    Adresse: str
    Kapacitet: int
    Lokationstype: str
    }
class Kurser{
    Kursus ID: int
    ECTS: float
    Student liste: list
    Kursusansvarlig: str
    }
class Skema{
    Skema liste : list
    ugenr : liste
    datetime
    --
    VisSkema():
    }
class Forelæsning{
    Tidspunkt: datetime
    Kursus: str
    Hold: str
    Lokale: str
    --
    AngivKursus():
    AngivHold():
    AngivLokale():
    }
class Semester{
    Årgang: int
    Semesterniveau: int
    --
    Semester: list(Kurser)
    }
class Studieretning{
    Studieretning ID: int
    Navn: str
    Fakultet: str
    Uddannelsesniveau: str
    }

@enduml