@startuml
Login <|-- Bruger
Forside <|-- Login
Hovedmenu <|-- Forside
Skema <|-- Hovedmenu
Lokaler <|-- Hovedmenu
Indstillinger <|-- Hovedmenu
Beskeder <|-- Hovedmenu


Bruger : Studerende
Bruger : Lærer / TA
Bruger : SkemaSekretær

Login : Login via Universitetoplysninger

Forside : Dagens summary
Forside : Hovedmenu

Hovedmenu : Skema
Hovedmenu : Lokaler
Hovedmenu : Indstillinger
Hovedmenu : Beskeder

Skema : SeSkema
Skema : RedigerSkema
Skema : AnmodSkemaÆndring

Lokaler : LokaleTilgængelighed

Indstillinger : Support
Indstillinger : Indstillinger

Beskeder : SkemaÆndringer
Beskeder : BeskederFraLærere




@enduml