@startuml
Actor Lærer
Activate Lærer
Lærer -> Uniskema: Login
Activate Uniskema
Uniskema -> Database: Tjek bruger
Activate Database
Actor SkemaSekretær
alt successful login
    Uniskema <- Database: Bruger godkendt
    Lærer <- Uniskema: Menu
else failed login
    Uniskema <- Database: Bruger ikke godkendt
    Lærer <- Uniskema: Logout
end
Lærer -> Uniskema: Søger efter sit skema
Uniskema -> Database: Finder Lærerens skema
Uniskema <- Database: Henter skemaet til Læreren
Lærer <- Uniskema: Viser skemaet til Læreren
Lærer -> Uniskema: Anmod om ændring af skemaet
Uniskema -> Database: Anmodning lagres i databasen
Database -> SkemaSekretær: Sender besked til SkemaSekretær
return End connection
return Logout
@enduml