@startuml

Actor Lærer
Lærer -> Uniskema: Leder efter lokale
Activate Uniskema
Uniskema -> Uniskema_Service: Fremsøger data
Activate Uniskema_Service
Uniskema_Service -> Database: Fremsøger data
Activate Database
Database -> Universiteter: Løbende søgning af lokale
Activate Universiteter
Return Løbende sending af lokale
Return Sender data
Uniskema <- Uniskema_Service: Viser lokale
@enduml