@startuml
Actor Studerende
Studerende -> Uniskema: Login
Activate Uniskema
Uniskema -> Uniskema_Service: Tjek bruger
Activate Uniskema_Service
alt successfuld login
    Uniskema <-- Uniskema_Service: Bruger godkendt
    Studerende <- Uniskema: Menu
else Bruger ikke fundet
    Return Bruger ikke godkendt
    Studerende <- Uniskema: Log ud
end

@enduml