@startuml
top to bottom direction
package "Lag1 - Brugere" as l1 {
[Studerende]
[Lærere]
[Skemasekretær]
}
package "Lag2 - Præsentation" as l2 {
[UniSkema]
}
package "Lag3 - Logik" as l3 {
[UniSkema service]
}
package "Lag4 - Sikkerhed" as l4 {
[UniSkema sikkerhed] as a
}
package "Lag5 - Common data" as l5 {
[SQL database]
}


l1 -> l4
l2 -> l4
l4 <- l3
l4 <- l5

[Studerende] ..> [UniSkema]
[Skemasekretær] ..> [UniSkema]
[Lærere] ..> [UniSkema]
[UniSkema] ..> [UniSkema service]
[UniSkema service] ..> [SQL database]

@enduml
