@startuml
left to right direction
:Studerende:
rectangle "UniSkema"  {
Studerende --> (Ønsker at se skemaet for en specifik dag)
}
actor Studerende as Studerende2 
rectangle "UniSkema" as "UniSkema5" {
Studerende2 --> (Ønsker at se skemaet for hele semesteret)
}

:Lærer:
rectangle "UniSkema" as "UniSkema2" {
Lærer --> (Ønsker at se tidspunktet for undervisningen)
}

actor Lærer as Lærer2
rectangle "UniSkema" as "UniSkema4"  {
Lærer2 --> (Ønsker at ændre tidspunktet for en forelæsning)
(Ønsker at ændre tidspunktet for en forelæsning) --> (Vælger nyt tidspunkt for forelæsning)
(Vælger nyt tidspunkt for forelæsning) --> (Anmodning bliver genereret)
}
(Anmodning bliver genereret) --> :SkemaSekretær:

actor SkemaSekretær as SkemaSekretær2
rectangle "UniSkema" as "UniSkema3"  {
SkemaSekretær2 --> (En lærer har henvendt sig omkring ændring af undervisning)
(En lærer har henvendt sig omkring ændring af undervisning) --> (Redigere skemaet)
}
@enduml
