@startuml
autonumber
Actor Lærer
Activate Lærer
Lærer -> Uniskema: Login
Activate Uniskema
Uniskema -> Database: Tjek bruger
Activate Database
alt successful login
    Uniskema <-- Database: Bruger godkendt
    Lærer <-- Uniskema: Menu
else failed login
    Uniskema <-- Database: Bruger ikke godkendt
    Lærer <-- Uniskema: Logout
end
Lærer -> Uniskema: Se skema
Uniskema -> Database: Finder skema
Uniskema <-- Database: Henter skema
Lærer <-- Uniskema: Vis skema
Lærer -> Uniskema: Foreslå skemaændring
Uniskema -> Database: Anmodning lagres i databasen
return End connection
return Logout
@enduml
