@startuml
autonumber
Actor SkemaSekretær
SkemaSekretær -> Uniskema: Login
Activate Uniskema
Uniskema -> Database: Tjek bruger
Activate Database
Actor Lærer
alt successful login
    Uniskema <-- Database: Bruger godkendt
    SkemaSekretær <-- Uniskema: Menu
else failed login
    Uniskema <-- Database: Bruger ikke godkendt
    SkemaSekretær <-- Uniskema: Logout
end
SkemaSekretær -> Uniskema: Besvar anmodning
Uniskema -> Database: Finder Lærerens anmodning
Uniskema <-- Database: Henter Lærerens anmodning
SkemaSekretær <-- Uniskema: Viser Lærerens anmodning
SkemaSekretær -> Uniskema: Søger efter de involveredes skemaer
Uniskema -> Database: Finder de involveredes skemaer
Uniskema <-- Database: Henter de involveredes skemaer
SkemaSekretær <-- Uniskema: Viser de involveredes skemaer
alt Godkendelse
    SkemaSekretær -> Uniskema: Lærerens anmodning godkendes
    Uniskema -> Database: Redigere skema
    Uniskema <-- Database: Skema opdateret
    SkemaSekretær <-- Uniskema: Vis skema
    SkemaSekretær -> Uniskema: Besvarer at lærerens anmodning godkendes
    Uniskema -> Database: Besked lagres i databasen
    Database -> Lærer: Sender besked til Læreren
else Afvisning
    SkemaSekretær -> Uniskema: Besvarer at lærerens anmodning afvises
    Uniskema -> Database: Besked lagres i databasen
    Database -> Lærer: Sender besked til Læreren
end
return End connection
return logout
@enduml